package server;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Front_end.proto

public final class FrontEnd {
  private FrontEnd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FpurchaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Fpurchase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 packege_id = 1;</code>
     */
    boolean hasPackegeId();
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    long getPackegeId();
  }
  /**
   * Protobuf type {@code Fpurchase}
   */
  public  static final class Fpurchase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Fpurchase)
      FpurchaseOrBuilder {
    // Use Fpurchase.newBuilder() to construct.
    private Fpurchase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Fpurchase() {
      packegeId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Fpurchase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              packegeId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrontEnd.internal_static_Fpurchase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrontEnd.internal_static_Fpurchase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FrontEnd.Fpurchase.class, FrontEnd.Fpurchase.Builder.class);
    }

    private int bitField0_;
    public static final int PACKEGE_ID_FIELD_NUMBER = 1;
    private long packegeId_;
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    public boolean hasPackegeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    public long getPackegeId() {
      return packegeId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackegeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, packegeId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packegeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FrontEnd.Fpurchase)) {
        return super.equals(obj);
      }
      FrontEnd.Fpurchase other = (FrontEnd.Fpurchase) obj;

      boolean result = true;
      result = result && (hasPackegeId() == other.hasPackegeId());
      if (hasPackegeId()) {
        result = result && (getPackegeId()
            == other.getPackegeId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPackegeId()) {
        hash = (37 * hash) + PACKEGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPackegeId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FrontEnd.Fpurchase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.Fpurchase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.Fpurchase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.Fpurchase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.Fpurchase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.Fpurchase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.Fpurchase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FrontEnd.Fpurchase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.Fpurchase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.Fpurchase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FrontEnd.Fpurchase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Fpurchase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Fpurchase)
        FrontEnd.FpurchaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrontEnd.internal_static_Fpurchase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrontEnd.internal_static_Fpurchase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FrontEnd.Fpurchase.class, FrontEnd.Fpurchase.Builder.class);
      }

      // Construct using FrontEnd.Fpurchase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        packegeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrontEnd.internal_static_Fpurchase_descriptor;
      }

      public FrontEnd.Fpurchase getDefaultInstanceForType() {
        return FrontEnd.Fpurchase.getDefaultInstance();
      }

      public FrontEnd.Fpurchase build() {
        FrontEnd.Fpurchase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FrontEnd.Fpurchase buildPartial() {
        FrontEnd.Fpurchase result = new FrontEnd.Fpurchase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packegeId_ = packegeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FrontEnd.Fpurchase) {
          return mergeFrom((FrontEnd.Fpurchase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FrontEnd.Fpurchase other) {
        if (other == FrontEnd.Fpurchase.getDefaultInstance()) return this;
        if (other.hasPackegeId()) {
          setPackegeId(other.getPackegeId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPackegeId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FrontEnd.Fpurchase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FrontEnd.Fpurchase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long packegeId_ ;
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public boolean hasPackegeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public long getPackegeId() {
        return packegeId_;
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public Builder setPackegeId(long value) {
        bitField0_ |= 0x00000001;
        packegeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public Builder clearPackegeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packegeId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Fpurchase)
    }

    // @@protoc_insertion_point(class_scope:Fpurchase)
    private static final FrontEnd.Fpurchase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FrontEnd.Fpurchase();
    }

    public static FrontEnd.Fpurchase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Fpurchase>
        PARSER = new com.google.protobuf.AbstractParser<Fpurchase>() {
      public Fpurchase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Fpurchase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Fpurchase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Fpurchase> getParserForType() {
      return PARSER;
    }

    public FrontEnd.Fpurchase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FcancelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Fcancel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 packege_id = 1;</code>
     */
    boolean hasPackegeId();
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    long getPackegeId();
  }
  /**
   * Protobuf type {@code Fcancel}
   */
  public  static final class Fcancel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Fcancel)
      FcancelOrBuilder {
    // Use Fcancel.newBuilder() to construct.
    private Fcancel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Fcancel() {
      packegeId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Fcancel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              packegeId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrontEnd.internal_static_Fcancel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrontEnd.internal_static_Fcancel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FrontEnd.Fcancel.class, FrontEnd.Fcancel.Builder.class);
    }

    private int bitField0_;
    public static final int PACKEGE_ID_FIELD_NUMBER = 1;
    private long packegeId_;
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    public boolean hasPackegeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    public long getPackegeId() {
      return packegeId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackegeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, packegeId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packegeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FrontEnd.Fcancel)) {
        return super.equals(obj);
      }
      FrontEnd.Fcancel other = (FrontEnd.Fcancel) obj;

      boolean result = true;
      result = result && (hasPackegeId() == other.hasPackegeId());
      if (hasPackegeId()) {
        result = result && (getPackegeId()
            == other.getPackegeId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPackegeId()) {
        hash = (37 * hash) + PACKEGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPackegeId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FrontEnd.Fcancel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.Fcancel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.Fcancel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.Fcancel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.Fcancel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.Fcancel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.Fcancel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FrontEnd.Fcancel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.Fcancel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.Fcancel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FrontEnd.Fcancel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Fcancel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Fcancel)
        FrontEnd.FcancelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrontEnd.internal_static_Fcancel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrontEnd.internal_static_Fcancel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FrontEnd.Fcancel.class, FrontEnd.Fcancel.Builder.class);
      }

      // Construct using FrontEnd.Fcancel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        packegeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrontEnd.internal_static_Fcancel_descriptor;
      }

      public FrontEnd.Fcancel getDefaultInstanceForType() {
        return FrontEnd.Fcancel.getDefaultInstance();
      }

      public FrontEnd.Fcancel build() {
        FrontEnd.Fcancel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FrontEnd.Fcancel buildPartial() {
        FrontEnd.Fcancel result = new FrontEnd.Fcancel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packegeId_ = packegeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FrontEnd.Fcancel) {
          return mergeFrom((FrontEnd.Fcancel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FrontEnd.Fcancel other) {
        if (other == FrontEnd.Fcancel.getDefaultInstance()) return this;
        if (other.hasPackegeId()) {
          setPackegeId(other.getPackegeId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPackegeId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FrontEnd.Fcancel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FrontEnd.Fcancel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long packegeId_ ;
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public boolean hasPackegeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public long getPackegeId() {
        return packegeId_;
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public Builder setPackegeId(long value) {
        bitField0_ |= 0x00000001;
        packegeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public Builder clearPackegeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packegeId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Fcancel)
    }

    // @@protoc_insertion_point(class_scope:Fcancel)
    private static final FrontEnd.Fcancel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FrontEnd.Fcancel();
    }

    public static FrontEnd.Fcancel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Fcancel>
        PARSER = new com.google.protobuf.AbstractParser<Fcancel>() {
      public Fcancel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Fcancel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Fcancel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Fcancel> getParserForType() {
      return PARSER;
    }

    public FrontEnd.Fcancel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Fchange_destOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Fchange_dest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 packege_id = 1;</code>
     */
    boolean hasPackegeId();
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    long getPackegeId();

    /**
     * <code>required int32 new_x = 2;</code>
     */
    boolean hasNewX();
    /**
     * <code>required int32 new_x = 2;</code>
     */
    int getNewX();

    /**
     * <code>required int32 new_y = 3;</code>
     */
    boolean hasNewY();
    /**
     * <code>required int32 new_y = 3;</code>
     */
    int getNewY();
  }
  /**
   * Protobuf type {@code Fchange_dest}
   */
  public  static final class Fchange_dest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Fchange_dest)
      Fchange_destOrBuilder {
    // Use Fchange_dest.newBuilder() to construct.
    private Fchange_dest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Fchange_dest() {
      packegeId_ = 0L;
      newX_ = 0;
      newY_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Fchange_dest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              packegeId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              newX_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              newY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrontEnd.internal_static_Fchange_dest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrontEnd.internal_static_Fchange_dest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FrontEnd.Fchange_dest.class, FrontEnd.Fchange_dest.Builder.class);
    }

    private int bitField0_;
    public static final int PACKEGE_ID_FIELD_NUMBER = 1;
    private long packegeId_;
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    public boolean hasPackegeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 packege_id = 1;</code>
     */
    public long getPackegeId() {
      return packegeId_;
    }

    public static final int NEW_X_FIELD_NUMBER = 2;
    private int newX_;
    /**
     * <code>required int32 new_x = 2;</code>
     */
    public boolean hasNewX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 new_x = 2;</code>
     */
    public int getNewX() {
      return newX_;
    }

    public static final int NEW_Y_FIELD_NUMBER = 3;
    private int newY_;
    /**
     * <code>required int32 new_y = 3;</code>
     */
    public boolean hasNewY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 new_y = 3;</code>
     */
    public int getNewY() {
      return newY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackegeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, packegeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, newX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, newY_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packegeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, newX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, newY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FrontEnd.Fchange_dest)) {
        return super.equals(obj);
      }
      FrontEnd.Fchange_dest other = (FrontEnd.Fchange_dest) obj;

      boolean result = true;
      result = result && (hasPackegeId() == other.hasPackegeId());
      if (hasPackegeId()) {
        result = result && (getPackegeId()
            == other.getPackegeId());
      }
      result = result && (hasNewX() == other.hasNewX());
      if (hasNewX()) {
        result = result && (getNewX()
            == other.getNewX());
      }
      result = result && (hasNewY() == other.hasNewY());
      if (hasNewY()) {
        result = result && (getNewY()
            == other.getNewY());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPackegeId()) {
        hash = (37 * hash) + PACKEGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPackegeId());
      }
      if (hasNewX()) {
        hash = (37 * hash) + NEW_X_FIELD_NUMBER;
        hash = (53 * hash) + getNewX();
      }
      if (hasNewY()) {
        hash = (37 * hash) + NEW_Y_FIELD_NUMBER;
        hash = (53 * hash) + getNewY();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FrontEnd.Fchange_dest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.Fchange_dest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.Fchange_dest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.Fchange_dest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.Fchange_dest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.Fchange_dest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.Fchange_dest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FrontEnd.Fchange_dest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.Fchange_dest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.Fchange_dest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FrontEnd.Fchange_dest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Fchange_dest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Fchange_dest)
        FrontEnd.Fchange_destOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrontEnd.internal_static_Fchange_dest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrontEnd.internal_static_Fchange_dest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FrontEnd.Fchange_dest.class, FrontEnd.Fchange_dest.Builder.class);
      }

      // Construct using FrontEnd.Fchange_dest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        packegeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        newX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        newY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrontEnd.internal_static_Fchange_dest_descriptor;
      }

      public FrontEnd.Fchange_dest getDefaultInstanceForType() {
        return FrontEnd.Fchange_dest.getDefaultInstance();
      }

      public FrontEnd.Fchange_dest build() {
        FrontEnd.Fchange_dest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FrontEnd.Fchange_dest buildPartial() {
        FrontEnd.Fchange_dest result = new FrontEnd.Fchange_dest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packegeId_ = packegeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newX_ = newX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.newY_ = newY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FrontEnd.Fchange_dest) {
          return mergeFrom((FrontEnd.Fchange_dest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FrontEnd.Fchange_dest other) {
        if (other == FrontEnd.Fchange_dest.getDefaultInstance()) return this;
        if (other.hasPackegeId()) {
          setPackegeId(other.getPackegeId());
        }
        if (other.hasNewX()) {
          setNewX(other.getNewX());
        }
        if (other.hasNewY()) {
          setNewY(other.getNewY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPackegeId()) {
          return false;
        }
        if (!hasNewX()) {
          return false;
        }
        if (!hasNewY()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FrontEnd.Fchange_dest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FrontEnd.Fchange_dest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long packegeId_ ;
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public boolean hasPackegeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public long getPackegeId() {
        return packegeId_;
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public Builder setPackegeId(long value) {
        bitField0_ |= 0x00000001;
        packegeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 packege_id = 1;</code>
       */
      public Builder clearPackegeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packegeId_ = 0L;
        onChanged();
        return this;
      }

      private int newX_ ;
      /**
       * <code>required int32 new_x = 2;</code>
       */
      public boolean hasNewX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 new_x = 2;</code>
       */
      public int getNewX() {
        return newX_;
      }
      /**
       * <code>required int32 new_x = 2;</code>
       */
      public Builder setNewX(int value) {
        bitField0_ |= 0x00000002;
        newX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 new_x = 2;</code>
       */
      public Builder clearNewX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newX_ = 0;
        onChanged();
        return this;
      }

      private int newY_ ;
      /**
       * <code>required int32 new_y = 3;</code>
       */
      public boolean hasNewY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 new_y = 3;</code>
       */
      public int getNewY() {
        return newY_;
      }
      /**
       * <code>required int32 new_y = 3;</code>
       */
      public Builder setNewY(int value) {
        bitField0_ |= 0x00000004;
        newY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 new_y = 3;</code>
       */
      public Builder clearNewY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newY_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Fchange_dest)
    }

    // @@protoc_insertion_point(class_scope:Fchange_dest)
    private static final FrontEnd.Fchange_dest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FrontEnd.Fchange_dest();
    }

    public static FrontEnd.Fchange_dest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Fchange_dest>
        PARSER = new com.google.protobuf.AbstractParser<Fchange_dest>() {
      public Fchange_dest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Fchange_dest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Fchange_dest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Fchange_dest> getParserForType() {
      return PARSER;
    }

    public FrontEnd.Fchange_dest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FECommandsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FECommands)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Fpurchase purchase = 1;</code>
     */
    boolean hasPurchase();
    /**
     * <code>optional .Fpurchase purchase = 1;</code>
     */
    FrontEnd.Fpurchase getPurchase();
    /**
     * <code>optional .Fpurchase purchase = 1;</code>
     */
    FrontEnd.FpurchaseOrBuilder getPurchaseOrBuilder();

    /**
     * <code>optional .Fcancel cancel = 2;</code>
     */
    boolean hasCancel();
    /**
     * <code>optional .Fcancel cancel = 2;</code>
     */
    FrontEnd.Fcancel getCancel();
    /**
     * <code>optional .Fcancel cancel = 2;</code>
     */
    FrontEnd.FcancelOrBuilder getCancelOrBuilder();

    /**
     * <code>optional .Fchange_dest change = 3;</code>
     */
    boolean hasChange();
    /**
     * <code>optional .Fchange_dest change = 3;</code>
     */
    FrontEnd.Fchange_dest getChange();
    /**
     * <code>optional .Fchange_dest change = 3;</code>
     */
    FrontEnd.Fchange_destOrBuilder getChangeOrBuilder();
  }
  /**
   * Protobuf type {@code FECommands}
   */
  public  static final class FECommands extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FECommands)
      FECommandsOrBuilder {
    // Use FECommands.newBuilder() to construct.
    private FECommands(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FECommands() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FECommands(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              FrontEnd.Fpurchase.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = purchase_.toBuilder();
              }
              purchase_ = input.readMessage(FrontEnd.Fpurchase.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(purchase_);
                purchase_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              FrontEnd.Fcancel.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = cancel_.toBuilder();
              }
              cancel_ = input.readMessage(FrontEnd.Fcancel.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cancel_);
                cancel_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              FrontEnd.Fchange_dest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = change_.toBuilder();
              }
              change_ = input.readMessage(FrontEnd.Fchange_dest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(change_);
                change_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrontEnd.internal_static_FECommands_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrontEnd.internal_static_FECommands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FrontEnd.FECommands.class, FrontEnd.FECommands.Builder.class);
    }

    private int bitField0_;
    public static final int PURCHASE_FIELD_NUMBER = 1;
    private FrontEnd.Fpurchase purchase_;
    /**
     * <code>optional .Fpurchase purchase = 1;</code>
     */
    public boolean hasPurchase() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Fpurchase purchase = 1;</code>
     */
    public FrontEnd.Fpurchase getPurchase() {
      return purchase_ == null ? FrontEnd.Fpurchase.getDefaultInstance() : purchase_;
    }
    /**
     * <code>optional .Fpurchase purchase = 1;</code>
     */
    public FrontEnd.FpurchaseOrBuilder getPurchaseOrBuilder() {
      return purchase_ == null ? FrontEnd.Fpurchase.getDefaultInstance() : purchase_;
    }

    public static final int CANCEL_FIELD_NUMBER = 2;
    private FrontEnd.Fcancel cancel_;
    /**
     * <code>optional .Fcancel cancel = 2;</code>
     */
    public boolean hasCancel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Fcancel cancel = 2;</code>
     */
    public FrontEnd.Fcancel getCancel() {
      return cancel_ == null ? FrontEnd.Fcancel.getDefaultInstance() : cancel_;
    }
    /**
     * <code>optional .Fcancel cancel = 2;</code>
     */
    public FrontEnd.FcancelOrBuilder getCancelOrBuilder() {
      return cancel_ == null ? FrontEnd.Fcancel.getDefaultInstance() : cancel_;
    }

    public static final int CHANGE_FIELD_NUMBER = 3;
    private FrontEnd.Fchange_dest change_;
    /**
     * <code>optional .Fchange_dest change = 3;</code>
     */
    public boolean hasChange() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Fchange_dest change = 3;</code>
     */
    public FrontEnd.Fchange_dest getChange() {
      return change_ == null ? FrontEnd.Fchange_dest.getDefaultInstance() : change_;
    }
    /**
     * <code>optional .Fchange_dest change = 3;</code>
     */
    public FrontEnd.Fchange_destOrBuilder getChangeOrBuilder() {
      return change_ == null ? FrontEnd.Fchange_dest.getDefaultInstance() : change_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasPurchase()) {
        if (!getPurchase().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCancel()) {
        if (!getCancel().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasChange()) {
        if (!getChange().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getPurchase());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getCancel());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getChange());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPurchase());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCancel());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getChange());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FrontEnd.FECommands)) {
        return super.equals(obj);
      }
      FrontEnd.FECommands other = (FrontEnd.FECommands) obj;

      boolean result = true;
      result = result && (hasPurchase() == other.hasPurchase());
      if (hasPurchase()) {
        result = result && getPurchase()
            .equals(other.getPurchase());
      }
      result = result && (hasCancel() == other.hasCancel());
      if (hasCancel()) {
        result = result && getCancel()
            .equals(other.getCancel());
      }
      result = result && (hasChange() == other.hasChange());
      if (hasChange()) {
        result = result && getChange()
            .equals(other.getChange());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPurchase()) {
        hash = (37 * hash) + PURCHASE_FIELD_NUMBER;
        hash = (53 * hash) + getPurchase().hashCode();
      }
      if (hasCancel()) {
        hash = (37 * hash) + CANCEL_FIELD_NUMBER;
        hash = (53 * hash) + getCancel().hashCode();
      }
      if (hasChange()) {
        hash = (37 * hash) + CHANGE_FIELD_NUMBER;
        hash = (53 * hash) + getChange().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FrontEnd.FECommands parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.FECommands parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.FECommands parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEnd.FECommands parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEnd.FECommands parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.FECommands parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.FECommands parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FrontEnd.FECommands parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEnd.FECommands parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEnd.FECommands parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FrontEnd.FECommands prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FECommands}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FECommands)
        FrontEnd.FECommandsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrontEnd.internal_static_FECommands_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrontEnd.internal_static_FECommands_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FrontEnd.FECommands.class, FrontEnd.FECommands.Builder.class);
      }

      // Construct using FrontEnd.FECommands.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPurchaseFieldBuilder();
          getCancelFieldBuilder();
          getChangeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (purchaseBuilder_ == null) {
          purchase_ = null;
        } else {
          purchaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (cancelBuilder_ == null) {
          cancel_ = null;
        } else {
          cancelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (changeBuilder_ == null) {
          change_ = null;
        } else {
          changeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrontEnd.internal_static_FECommands_descriptor;
      }

      public FrontEnd.FECommands getDefaultInstanceForType() {
        return FrontEnd.FECommands.getDefaultInstance();
      }

      public FrontEnd.FECommands build() {
        FrontEnd.FECommands result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FrontEnd.FECommands buildPartial() {
        FrontEnd.FECommands result = new FrontEnd.FECommands(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (purchaseBuilder_ == null) {
          result.purchase_ = purchase_;
        } else {
          result.purchase_ = purchaseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (cancelBuilder_ == null) {
          result.cancel_ = cancel_;
        } else {
          result.cancel_ = cancelBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (changeBuilder_ == null) {
          result.change_ = change_;
        } else {
          result.change_ = changeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FrontEnd.FECommands) {
          return mergeFrom((FrontEnd.FECommands)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FrontEnd.FECommands other) {
        if (other == FrontEnd.FECommands.getDefaultInstance()) return this;
        if (other.hasPurchase()) {
          mergePurchase(other.getPurchase());
        }
        if (other.hasCancel()) {
          mergeCancel(other.getCancel());
        }
        if (other.hasChange()) {
          mergeChange(other.getChange());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasPurchase()) {
          if (!getPurchase().isInitialized()) {
            return false;
          }
        }
        if (hasCancel()) {
          if (!getCancel().isInitialized()) {
            return false;
          }
        }
        if (hasChange()) {
          if (!getChange().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FrontEnd.FECommands parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FrontEnd.FECommands) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private FrontEnd.Fpurchase purchase_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEnd.Fpurchase, FrontEnd.Fpurchase.Builder, FrontEnd.FpurchaseOrBuilder> purchaseBuilder_;
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public boolean hasPurchase() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public FrontEnd.Fpurchase getPurchase() {
        if (purchaseBuilder_ == null) {
          return purchase_ == null ? FrontEnd.Fpurchase.getDefaultInstance() : purchase_;
        } else {
          return purchaseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public Builder setPurchase(FrontEnd.Fpurchase value) {
        if (purchaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          purchase_ = value;
          onChanged();
        } else {
          purchaseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public Builder setPurchase(
          FrontEnd.Fpurchase.Builder builderForValue) {
        if (purchaseBuilder_ == null) {
          purchase_ = builderForValue.build();
          onChanged();
        } else {
          purchaseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public Builder mergePurchase(FrontEnd.Fpurchase value) {
        if (purchaseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              purchase_ != null &&
              purchase_ != FrontEnd.Fpurchase.getDefaultInstance()) {
            purchase_ =
              FrontEnd.Fpurchase.newBuilder(purchase_).mergeFrom(value).buildPartial();
          } else {
            purchase_ = value;
          }
          onChanged();
        } else {
          purchaseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public Builder clearPurchase() {
        if (purchaseBuilder_ == null) {
          purchase_ = null;
          onChanged();
        } else {
          purchaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public FrontEnd.Fpurchase.Builder getPurchaseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPurchaseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      public FrontEnd.FpurchaseOrBuilder getPurchaseOrBuilder() {
        if (purchaseBuilder_ != null) {
          return purchaseBuilder_.getMessageOrBuilder();
        } else {
          return purchase_ == null ?
              FrontEnd.Fpurchase.getDefaultInstance() : purchase_;
        }
      }
      /**
       * <code>optional .Fpurchase purchase = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEnd.Fpurchase, FrontEnd.Fpurchase.Builder, FrontEnd.FpurchaseOrBuilder> 
          getPurchaseFieldBuilder() {
        if (purchaseBuilder_ == null) {
          purchaseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FrontEnd.Fpurchase, FrontEnd.Fpurchase.Builder, FrontEnd.FpurchaseOrBuilder>(
                  getPurchase(),
                  getParentForChildren(),
                  isClean());
          purchase_ = null;
        }
        return purchaseBuilder_;
      }

      private FrontEnd.Fcancel cancel_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEnd.Fcancel, FrontEnd.Fcancel.Builder, FrontEnd.FcancelOrBuilder> cancelBuilder_;
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public boolean hasCancel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public FrontEnd.Fcancel getCancel() {
        if (cancelBuilder_ == null) {
          return cancel_ == null ? FrontEnd.Fcancel.getDefaultInstance() : cancel_;
        } else {
          return cancelBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public Builder setCancel(FrontEnd.Fcancel value) {
        if (cancelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cancel_ = value;
          onChanged();
        } else {
          cancelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public Builder setCancel(
          FrontEnd.Fcancel.Builder builderForValue) {
        if (cancelBuilder_ == null) {
          cancel_ = builderForValue.build();
          onChanged();
        } else {
          cancelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public Builder mergeCancel(FrontEnd.Fcancel value) {
        if (cancelBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              cancel_ != null &&
              cancel_ != FrontEnd.Fcancel.getDefaultInstance()) {
            cancel_ =
              FrontEnd.Fcancel.newBuilder(cancel_).mergeFrom(value).buildPartial();
          } else {
            cancel_ = value;
          }
          onChanged();
        } else {
          cancelBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public Builder clearCancel() {
        if (cancelBuilder_ == null) {
          cancel_ = null;
          onChanged();
        } else {
          cancelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public FrontEnd.Fcancel.Builder getCancelBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCancelFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      public FrontEnd.FcancelOrBuilder getCancelOrBuilder() {
        if (cancelBuilder_ != null) {
          return cancelBuilder_.getMessageOrBuilder();
        } else {
          return cancel_ == null ?
              FrontEnd.Fcancel.getDefaultInstance() : cancel_;
        }
      }
      /**
       * <code>optional .Fcancel cancel = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEnd.Fcancel, FrontEnd.Fcancel.Builder, FrontEnd.FcancelOrBuilder> 
          getCancelFieldBuilder() {
        if (cancelBuilder_ == null) {
          cancelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FrontEnd.Fcancel, FrontEnd.Fcancel.Builder, FrontEnd.FcancelOrBuilder>(
                  getCancel(),
                  getParentForChildren(),
                  isClean());
          cancel_ = null;
        }
        return cancelBuilder_;
      }

      private FrontEnd.Fchange_dest change_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEnd.Fchange_dest, FrontEnd.Fchange_dest.Builder, FrontEnd.Fchange_destOrBuilder> changeBuilder_;
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public boolean hasChange() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public FrontEnd.Fchange_dest getChange() {
        if (changeBuilder_ == null) {
          return change_ == null ? FrontEnd.Fchange_dest.getDefaultInstance() : change_;
        } else {
          return changeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public Builder setChange(FrontEnd.Fchange_dest value) {
        if (changeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          change_ = value;
          onChanged();
        } else {
          changeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public Builder setChange(
          FrontEnd.Fchange_dest.Builder builderForValue) {
        if (changeBuilder_ == null) {
          change_ = builderForValue.build();
          onChanged();
        } else {
          changeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public Builder mergeChange(FrontEnd.Fchange_dest value) {
        if (changeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              change_ != null &&
              change_ != FrontEnd.Fchange_dest.getDefaultInstance()) {
            change_ =
              FrontEnd.Fchange_dest.newBuilder(change_).mergeFrom(value).buildPartial();
          } else {
            change_ = value;
          }
          onChanged();
        } else {
          changeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public Builder clearChange() {
        if (changeBuilder_ == null) {
          change_ = null;
          onChanged();
        } else {
          changeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public FrontEnd.Fchange_dest.Builder getChangeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getChangeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      public FrontEnd.Fchange_destOrBuilder getChangeOrBuilder() {
        if (changeBuilder_ != null) {
          return changeBuilder_.getMessageOrBuilder();
        } else {
          return change_ == null ?
              FrontEnd.Fchange_dest.getDefaultInstance() : change_;
        }
      }
      /**
       * <code>optional .Fchange_dest change = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEnd.Fchange_dest, FrontEnd.Fchange_dest.Builder, FrontEnd.Fchange_destOrBuilder> 
          getChangeFieldBuilder() {
        if (changeBuilder_ == null) {
          changeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FrontEnd.Fchange_dest, FrontEnd.Fchange_dest.Builder, FrontEnd.Fchange_destOrBuilder>(
                  getChange(),
                  getParentForChildren(),
                  isClean());
          change_ = null;
        }
        return changeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FECommands)
    }

    // @@protoc_insertion_point(class_scope:FECommands)
    private static final FrontEnd.FECommands DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FrontEnd.FECommands();
    }

    public static FrontEnd.FECommands getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FECommands>
        PARSER = new com.google.protobuf.AbstractParser<FECommands>() {
      public FECommands parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FECommands(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FECommands> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FECommands> getParserForType() {
      return PARSER;
    }

    public FrontEnd.FECommands getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fpurchase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fpurchase_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fcancel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fcancel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fchange_dest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fchange_dest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FECommands_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FECommands_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Front_end.proto\"\037\n\tFpurchase\022\022\n\npackeg" +
      "e_id\030\001 \002(\003\"\035\n\007Fcancel\022\022\n\npackege_id\030\001 \002(" +
      "\003\"@\n\014Fchange_dest\022\022\n\npackege_id\030\001 \002(\003\022\r\n" +
      "\005new_x\030\002 \002(\005\022\r\n\005new_y\030\003 \002(\005\"c\n\nFECommand" +
      "s\022\034\n\010purchase\030\001 \001(\0132\n.Fpurchase\022\030\n\006cance" +
      "l\030\002 \001(\0132\010.Fcancel\022\035\n\006change\030\003 \001(\0132\r.Fcha" +
      "nge_dest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Fpurchase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Fpurchase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fpurchase_descriptor,
        new java.lang.String[] { "PackegeId", });
    internal_static_Fcancel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Fcancel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fcancel_descriptor,
        new java.lang.String[] { "PackegeId", });
    internal_static_Fchange_dest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Fchange_dest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fchange_dest_descriptor,
        new java.lang.String[] { "PackegeId", "NewX", "NewY", });
    internal_static_FECommands_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FECommands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FECommands_descriptor,
        new java.lang.String[] { "Purchase", "Cancel", "Change", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
