# Generated by Django 3.1.5 on 2021-04-20 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('whid', models.IntegerField(primary_key=True, serialize=False)),
                ('wh_x', models.IntegerField()),
                ('wh_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=256)),
                ('amounts', models.IntegerField()),
                ('price', models.FloatField(default=1)),
                ('wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_web.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('packege_id', models.AutoField(primary_key=True, serialize=False)),
                ('amounts', models.IntegerField()),
                ('price', models.FloatField(default=1)),
                ('truck_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='cart', max_length=20)),
                ('destination_x', models.IntegerField(null=True)),
                ('destination_y', models.IntegerField(null=True)),
                ('ups', models.CharField(blank=True, max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon_web.product')),
                ('wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_web.warehouse')),
            ],
        ),
    ]
