# Generated by Django 3.1.5 on 2021-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='people_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=5),
        ),
    ]
