# Generated by Django 3.1.5 on 2021-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0003_auto_20210422_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
