# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Front_end.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Front_end.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x46ront_end.proto\"\x1f\n\tFpurchase\x12\x12\n\npackege_id\x18\x01 \x02(\x03\"\x1d\n\x07\x46\x63\x61ncel\x12\x12\n\npackege_id\x18\x01 \x02(\x03\"@\n\x0c\x46\x63hange_dest\x12\x12\n\npackege_id\x18\x01 \x02(\x03\x12\r\n\x05new_x\x18\x02 \x02(\x05\x12\r\n\x05new_y\x18\x03 \x02(\x05\"c\n\nFECommands\x12\x1c\n\x08purchase\x18\x01 \x01(\x0b\x32\n.Fpurchase\x12\x18\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x08.Fcancel\x12\x1d\n\x06\x63hange\x18\x03 \x01(\x0b\x32\r.Fchange_dest')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FPURCHASE = _descriptor.Descriptor(
  name='Fpurchase',
  full_name='Fpurchase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packege_id', full_name='Fpurchase.packege_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=50,
)


_FCANCEL = _descriptor.Descriptor(
  name='Fcancel',
  full_name='Fcancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packege_id', full_name='Fcancel.packege_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=81,
)


_FCHANGE_DEST = _descriptor.Descriptor(
  name='Fchange_dest',
  full_name='Fchange_dest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packege_id', full_name='Fchange_dest.packege_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_x', full_name='Fchange_dest.new_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_y', full_name='Fchange_dest.new_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=147,
)


_FECOMMANDS = _descriptor.Descriptor(
  name='FECommands',
  full_name='FECommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='purchase', full_name='FECommands.purchase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cancel', full_name='FECommands.cancel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change', full_name='FECommands.change', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=248,
)

_FECOMMANDS.fields_by_name['purchase'].message_type = _FPURCHASE
_FECOMMANDS.fields_by_name['cancel'].message_type = _FCANCEL
_FECOMMANDS.fields_by_name['change'].message_type = _FCHANGE_DEST
DESCRIPTOR.message_types_by_name['Fpurchase'] = _FPURCHASE
DESCRIPTOR.message_types_by_name['Fcancel'] = _FCANCEL
DESCRIPTOR.message_types_by_name['Fchange_dest'] = _FCHANGE_DEST
DESCRIPTOR.message_types_by_name['FECommands'] = _FECOMMANDS

Fpurchase = _reflection.GeneratedProtocolMessageType('Fpurchase', (_message.Message,), dict(
  DESCRIPTOR = _FPURCHASE,
  __module__ = 'Front_end_pb2'
  # @@protoc_insertion_point(class_scope:Fpurchase)
  ))
_sym_db.RegisterMessage(Fpurchase)

Fcancel = _reflection.GeneratedProtocolMessageType('Fcancel', (_message.Message,), dict(
  DESCRIPTOR = _FCANCEL,
  __module__ = 'Front_end_pb2'
  # @@protoc_insertion_point(class_scope:Fcancel)
  ))
_sym_db.RegisterMessage(Fcancel)

Fchange_dest = _reflection.GeneratedProtocolMessageType('Fchange_dest', (_message.Message,), dict(
  DESCRIPTOR = _FCHANGE_DEST,
  __module__ = 'Front_end_pb2'
  # @@protoc_insertion_point(class_scope:Fchange_dest)
  ))
_sym_db.RegisterMessage(Fchange_dest)

FECommands = _reflection.GeneratedProtocolMessageType('FECommands', (_message.Message,), dict(
  DESCRIPTOR = _FECOMMANDS,
  __module__ = 'Front_end_pb2'
  # @@protoc_insertion_point(class_scope:FECommands)
  ))
_sym_db.RegisterMessage(FECommands)


# @@protoc_insertion_point(module_scope)
